export const DATA_FETCH = {
    REQUEST: 'DATA_FETCH_REQUEST',
    SUCCESS: 'DATA_FETCH_SUCCESS',
    INVALID: 'DATA_FETCH_INVALID',
    FAILURE: 'DATA_FETCH_FAILURE'
};

export const PROJECTS_FETCH = {
    REQUEST: 'PROJECTS_FETCH_REQUEST',
    SUCCESS: 'PROJECTS_FETCH_SUCCESS',
    INVALID: 'PROJECTS_FETCH_INVALID',
    FAILURE: 'PROJECTS_FETCH_FAILURE'
};

export const CREDENTIALS_FETCH = {
    REQUEST: 'CREDENTIALS_FETCH_REQUEST',
    SUCCESS: 'CREDENTIALS_FETCH_SUCCESS',
    INVALID: 'CREDENTIALS_FETCH_INVALID',
    FAILURE: 'CREDENTIALS_FETCH_FAILURE'
};

export const CREDENTIALS_LOGOUT = 'CREDENTIALS_LOGOUT';