export const DATA_FETCH = {
    REQUEST: 'DATA_FETCH_REQUEST',
    SUCCESS: 'DATA_FETCH_SUCCESS',
    INVALID: 'DATA_FETCH_INVALID',
    FAILURE: 'DATA_FETCH_FAILURE'
};

export const PROJECTS_FETCH = {
    REQUEST: 'PROJECTS_FETCH_REQUEST',
    SUCCESS: 'PROJECTS_FETCH_SUCCESS',
    INVALID: 'PROJECTS_FETCH_INVALID',
    FAILURE: 'PROJECTS_FETCH_FAILURE'
};

export const PROJECT_FETCH = {
    REQUEST: 'PROJECT_FETCH_REQUEST',
    SUCCESS: 'PROJECT_FETCH_SUCCESS',
    INVALID: 'PROJECT_FETCH_INVALID',
    FAILURE: 'PROJECT_FETCH_FAILURE'
};

export const PROJECT_POST = {
    REQUEST: 'PROJECT_POST_REQUEST',
    SUCCESS: 'PROJECT_POST_SUCCESS',
    INVALID: 'PROJECT_POST_INVALID',
    FAILURE: 'PROJECT_POST_FAILURE',
};

export const COMPANIES_FETCH = {
    REQUEST: 'COMPANIES_FETCH_REQUEST',
    SUCCESS: 'COMPANIES_FETCH_SUCCESS',
    INVALID: 'COMPANIES_FETCH_INVALID',
    FAILURE: 'COMPANIES_FETCH_FAILURE',
};

export const COMPANY_FETCH = {
    REQUEST: 'COMPANY_FETCH_REQUEST',
    SUCCESS: 'COMPANY_FETCH_SUCCESS',
    INVALID: 'COMPANY_FETCH_INVALID',
    FAILURE: 'COMPANY_FETCH_FAILURE',
};

export const COMPANY_POST = {
    REQUEST: 'COMPANY_POST_REQUEST',
    SUCCESS: 'COMPANY_POST_SUCCESS',
    INVALID: 'COMPANY_POST_INVALID',
    FAILURE: 'COMPANY_POST_FAILURE',
};
export const STATUSES_FETCH = {
    REQUEST: 'STATUSES_FETCH_REQUEST',
    SUCCESS: 'STATUSES_FETCH_SUCCESS',
    INVALID: 'STATUSES_FETCH_INVALID',
    FAILURE: 'STATUSES_FETCH_FAILURE',
};

export const STATUS_FETCH = {
    REQUEST: 'STATUS_FETCH_REQUEST',
    SUCCESS: 'STATUS_FETCH_SUCCESS',
    INVALID: 'STATUS_FETCH_INVALID',
    FAILURE: 'STATUS_FETCH_FAILURE',
};

export const STATUS_POST = {
    REQUEST: 'STATUS_POST_REQUEST',
    SUCCESS: 'STATUS_POST_SUCCESS',
    INVALID: 'STATUS_POST_INVALID',
    FAILURE: 'STATUS_POST_FAILURE',
};

export const STAFF_MEMBERS_FETCH = {
    REQUEST: 'STAFF_MEMBERS_FETCH_REQUEST',
    SUCCESS: 'STAFF_MEMBERS_FETCH_SUCCESS',
    INVALID: 'STAFF_MEMBERS_FETCH_INVALID',
    FAILURE: 'STAFF_MEMBERS_FETCH_FAILURE',
};

export const STAFF_MEMBER_FETCH = {
    REQUEST: 'STAFF_MEMBER_FETCH_REQUEST',
    SUCCESS: 'STAFF_MEMBER_FETCH_SUCCESS',
    INVALID: 'STAFF_MEMBER_FETCH_INVALID',
    FAILURE: 'STAFF_MEMBER_FETCH_FAILURE',
};

export const STAFF_MEMBER_POST = {
    REQUEST: 'STAFF_MEMBER_POST_REQUEST',
    SUCCESS: 'STAFF_MEMBER_POST_SUCCESS',
    INVALID: 'STAFF_MEMBER_POST_INVALID',
    FAILURE: 'STAFF_MEMBER_POST_FAILURE',
};


export const JOBS_FETCH = {
    REQUEST: 'JOBS_FETCH_REQUEST',
    SUCCESS: 'JOBS_FETCH_SUCCESS',
    INVALID: 'JOBS_FETCH_INVALID',
    FAILURE: 'JOBS_FETCH_FAILURE'
};

export const JOB_FETCH = {
    REQUEST: 'JOB_FETCH_REQUEST',
    SUCCESS: 'JOB_FETCH_SUCCESS',
    INVALID: 'JOB_FETCH_INVALID',
    FAILURE: 'JOB_FETCH_FAILURE'
};

export const CREDENTIALS_FETCH = {
    REQUEST: 'CREDENTIALS_FETCH_REQUEST',
    SUCCESS: 'CREDENTIALS_FETCH_SUCCESS',
    INVALID: 'CREDENTIALS_FETCH_INVALID',
    FAILURE: 'CREDENTIALS_FETCH_FAILURE'
};

export const CREDENTIALS_LOGOUT = 'CREDENTIALS_LOGOUT';
