export const DATA_FETCH = {
    REQUEST: 'DATA_FETCH_REQUEST',
    SUCCESS: 'DATA_FETCH_SUCCESS',
    INVALID: 'DATA_FETCH_INVALID',
    FAILURE: 'DATA_FETCH_FAILURE'
};

export const PROJECTS_FETCH = {
    REQUEST: 'PROJECTS_FETCH_REQUEST',
    SUCCESS: 'PROJECTS_FETCH_SUCCESS',
    INVALID: 'PROJECTS_FETCH_INVALID',
    FAILURE: 'PROJECTS_FETCH_FAILURE'
};

export const PROJECT_FETCH = {
    REQUEST: 'PROJECT_FETCH_REQUEST',
    SUCCESS: 'PROJECT_FETCH_SUCCESS',
    INVALID: 'PROJECT_FETCH_INVALID',
    FAILURE: 'PROJECT_FETCH_FAILURE'
};

export const PROJECT_POST = {
    REQUEST: 'PROJECT_POST_REQUEST',
    SUCCESS: 'PROJECT_POST_SUCCESS',
    INVALID: 'PROJECT_POST_INVALID',
    FAILURE: 'PROJECT_POST_FAILURE',
};

export const JOBS_FETCH = {
    REQUEST: 'JOBS_FETCH_REQUEST',
    SUCCESS: 'JOBS_FETCH_SUCCESS',
    INVALID: 'JOBS_FETCH_INVALID',
    FAILURE: 'JOBS_FETCH_FAILURE'
};

export const JOB_FETCH = {
    REQUEST: 'JOB_FETCH_REQUEST',
    SUCCESS: 'JOB_FETCH_SUCCESS',
    INVALID: 'JOB_FETCH_INVALID',
    FAILURE: 'JOB_FETCH_FAILURE'
};

export const CREDENTIALS_FETCH = {
    REQUEST: 'CREDENTIALS_FETCH_REQUEST',
    SUCCESS: 'CREDENTIALS_FETCH_SUCCESS',
    INVALID: 'CREDENTIALS_FETCH_INVALID',
    FAILURE: 'CREDENTIALS_FETCH_FAILURE'
};

export const CREDENTIALS_LOGOUT = 'CREDENTIALS_LOGOUT';
